SELECT USER_NEW.* FROM USER_NEW, ROLE WHERE USER_NEW.ROLE_ID=ROLE.ID ORDER BY USER_NEW.NAME ASC;

SELECT * FROM USER_NEW LEFT JOIN ROLE ON USER_NEW.ROLE_ID=ROLE.ID ORDER BY ROLE.NAME, USER_NEW ASC;

SELECT USER_NEW.NAME FROM USER_NEW, ROLE WHERE USER_NEW.ROLE_ID=ROLE.ID;

SELECT USER_NEW.phonenumber, USER_NEW.emailid, profile.batch, department.name, profile.designation,experiences.company_name FROM USER_NEW 
INNER JOIN profile ON USER_NAME.id=profile.id
INNER JOIN degree ON profile.degree_id=degree.id
INNER JOIN degree ON degree.department_id=department.id
INNER JOIN experiences ON experiences.profile_id=profile.id
WHERE user_name.name="ProGrad" AND experiences.currentValue=3;

SELECT user_new.name, skill.name FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ID=ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID=PROFILE.ID
INNER JOIN PROFILE_SKILLS ON PROFILE.ID=PROFILE_SKILLS.ID
INNER JOIN SKILL ON SKILL.ID=PROFILE_SKILLS.SKILL_ID WHERE ROLE.NAME='Alumni';


SELECT user_new.name, experience.company_name FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ID=ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID=PROFILE.ID
INNER JOIN EXPERIENCE ON PROFILE.ID=EXPERIENCE.PROFILE_ID WHERE ROLE.NAME='Alumni';


SELECT user_new.name, experience.company_name FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID=ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID=PROFILE.ID
INNER JOIN EXPERIENCE ON PROFILE.ID=EXPERIENCE.PROFILE_ID WHERE ROLE.NAME='Alumni';


SELECT user_new.name, experience.company_name FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID=ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID=PROFILE.ID
INNER JOIN EXPERIENCE ON PROFILE.ID=EXPERIENCE.PROFILE_ID WHERE ROLE.NAME='Alumni' AND EXPERIENCE.CURRENTVALUE=1;

SELECT user_new.name, experience.company_name FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID=ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID=PROFILE.ID
INNER JOIN EXPERIENCE ON PROFILE.ID=EXPERIENCE.PROFILE_ID WHERE ROLE.NAME='Alumni' AND EXPERIENCE.CURRENTVALUE=1 AND PROFILE.BATCH='2008';


SELECT user_new.name, user_new.emailid, user_new.phonenumber, profile.address FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID=ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID=PROFILE.ID WHERE ROLE.NAME='Alumni' AND USER_NEW.PROFILE_ID!=NULL ORDER BY USER_NEW.NAME;


SELECT user_new.name, user_new.emailid, user_new.phonenumber, profile.address FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID=ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID=PROFILE.ID WHERE ROLE.NAME='Alumni' AND PROFILE.BATCH='2008' ORDER BY USER_NEW.NAME;


SELECT user_new.name, experience.company_name FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID=ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID=PROFILE.ID
INNER JOIN DEGREE ON PROFILE.DEGREE_ID=DEGREE.ID WHERE ROLE.NAME='ALUMNI' AND DEGREE.NAME='BSC_CT' ORDER BY USER_NEW.NAME;


SELECT user_new.name, experience.company_name FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID=ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID=PROFILE.ID
INNER JOIN DEGREE ON PROFILE.DEGREE_ID=DEGREE.ID
INNER JOIN DEPARTMENT ON DEGREE.DEPARTMENT_ID=DEGREE.ID WHERE ROLE.NAME='ALUMNI' AND DEPARTMENT.NAME='CSE' ORDER BY USER_NEW.NAME;

SELECT user_new.name, experience.company_name FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID=ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID=PROFILE.ID
INNER JOIN HIGHER_DEGREE ON HIGHER_DEGREE.PROFILE_ID=PROFILE.ID
INNER JOIN DEPARTMENT ON DEGREE.DEPARTMENT_ID=DEPARTMENT.ID WHERE ROLE.NAME='ALUMNI' AND HIGHER_DEGREE.UNIVERSITY_NAME!=NULL ORDER BY USER_NEW.NAME,HIGHER_DEGREE.UNIVERSITY_NAME;

SELECT user_new.name, experience.company_name FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID=ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID=PROFILE.ID
INNER JOIN HIGHER_DEGREE ON HIGHER_DEGREE.PROFILE_ID=PROFILE.ID
INNER JOIN DEPARTMENT ON DEGREE.DEPARTMENT_ID=DEPARTMENT.ID WHERE ROLE.NAME='ALUMNI' AND HIGHER_DEGREE.UNIVERSITY_NAME!=NULL ORDER BY USER_NEW.NAME,HIGHER_DEGREE.UNIVERSITY_NAME;


SELECT user_new.name, experience.company_name FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID=ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID=PROFILE.ID
INNER JOIN HIGHER_DEGREE ON HIGHER_DEGREE.PROFILE_ID=PROFILE.ID
INNER JOIN DEPARTMENT ON DEGREE.DEPARTMENT_ID=DEPARTMENT.ID WHERE ROLE.NAME='ALUMNI' AND HIGHER_DEGREE.UNIVERSITY_NAME='TEXAS UNIVERSITY' ORDER BY USER_NEW.NAME,HIGHER_DEGREE.UNIVERSITY_NAME;


SELECT USER_NEW.NAME,PROFILE.BATCH FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID=ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID=PROFILE.ID WHERE ROLE.NAME='ALUMNI' AND PROFILE.GENDER='FEMALE' ORDER BY USER_NEW.NAME;


SELECT USER_NEW.NAME,PROFILE.BATCH FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID=ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID=PROFILE.ID
INNER JOIN DEGREE ON PROFILE.DEGREE_ID=DEGREE.ID WHERE ROLE.NAME='ALUMNI' AND PROFILE.GENDER='FEMALE' ORDER BY USER_NEW.NAME;


SELECT USER_NEW.NAME,PROFILE.BATCH,DEGREE.NAME,DEPARTMENT.NAME FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID=ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID=PROFILE.ID
INNER JOIN DEGREE ON PROFILE.DEGREE_ID=DEGREE.ID
INNER JOIN DEPARTMENT ON DEGREE.DEPARTMENT_ID=DEPARTMENT.ID WHERE ROLE.NAME='ALUMNI' AND PROFILE.GENDER='FEMALE' ORDER BY USER_NEW.NAME;


SELECT DEGREE.NAME, DEPARTMENT.NAME FROM DEGREE INNER JOIN DEPARTMENT ON DEGREE.DEPARTMENT_ID=DEPARTMENT.ID ORDER BY DEGREE.NAME;


SELECT USER_NEW.NAME,PROFILE.DESIGNATION FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID=ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID=PROFILE.ID WHERE ROLE.NAME='ALUMNI' AND PROFILE.GENDER='MALE' ORDER BY USER_NEW.NAME;


SELECT user_new.name, profile.designation FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ID=ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID=PROFILE.ID
INNER JOIN EXPERIENCE ON PROFILE.ID=EXPERIENCE.PROFILE_ID where role.name='Alumni' and experience.currentValue=1 and experience.company_name='TCS' ORDER BY USER_NEW.NAME;


SELECT USER_NEW.NAME, QUERYTABLE.CONTENT FROM USER_NEW INNER JOIN QUERYTABLE ON QUERYTABLE.USER_ID=USER_NEW.ID ORDER BY USER_NEW.NAME;


SELECT USER_NEW.NAME, QUERYTABLE.CONTENT FROM USER_NEW INNER JOIN QUERYTABLE ON QUERYTABLE.USER_ID=USER_NEW.ID WHERE QUERYTABLE.PARENT_ID!=NULL ORDER BY USER_NEW.NAME;


SELECT USER_NEW.NAME,POST.CONTENT FROM USER_NEW INNER JOIN POST ON USER_NEW.ID=POST.USER_ID ORDER BY USER_NEW.NAME;


SELECT USER_NEW.NAME,POST.CONTENT FROM USER_NEW INNER JOIN POST ON USER_NEW.ID=POST.USER_ID 
INNER JOIN POST.PARENT_ID=POST_TYPE.ID WHERE POST_TYPE.NAME='TECHNOLOGY' ORDER BY USER_NEW.NAME,POST.DATEOF;


SELECT USER_NEW.NAME,POST.CONTENT FROM USER_NEW INNER JOIN POST ON USER_NEW.ID=POST.USER_ID WHERE POST.DATEOF='2013' ORDER BY USER_NEW.NAME,POST.DATEOF;


SELECT user_new.name, experience.company_name FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID=ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID=PROFILE.ID
INNER JOIN DEGREE ON PROFILE.DEGREE_ID=DEGREE.ID
INNER JOIN DEPARTMENT ON DEGREE.DEPARTMENT_ID=DEGREE.ID


SELECT USER_NEW.NAME,EVENT.NAME FROM USER_NEW INNER JOIN EVENT ON USER_NEW.ID=EVENT.ORGANISER_ID ORDER BY USER_NEW.NAME,EVENT.DATEOF DESC;


SELECT USER_NEW.NAME,EVENT.NAME FROM USER_NEW INNER JOIN EVENT ON USER_NEW.ID=EVENT.ORGANISER_ID
INNER JOIN ROLE ON USER_NEW.ROLE_ID=ROLE.ID WHERE ROLE.NAME='ALUMNI' ORDER BY USER_NEW.NAME,EVENT.DATEOF;


